##===- lib/Transforms/MDMap/Makefile -----------------------*- Makefile -*-===##

LEVEL = ../../..
LIBRARYNAME = LLVMMatchTest
LOADABLE_MODULE = 1
USEDLIBS = mappercore.a

include $(LEVEL)/Makefile.common

