##===- projects/sample/tools/Makefile ----------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=../../..

#
# List all of the subdirectories that we will compile.
#

TOOLNAME=riskevaldriver
#
# LIBRARYNAME = LLVMCostDriver
# LOADABLE_MODULE = 1
USEDLIBS = commons.a riskeval.a slicer.a dependence.a

# LLVMLIBS = LLVMSupport.a
LINK_COMPONENTS = all

include $(LEVEL)/Makefile.common
