##===- projects/sample/lib/sample/Makefile -----------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Give the name of a library.  This will build a dynamic version.
#
BUILD_ARCHIVE = 1
LIBRARYNAME = dependence 

# ARCHIVE_LIBRARY = 1
# USEDLIBS = graph.a
# LOADABLE_MODULE = 1


#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common
