##===- projects/sample/tools/Makefile ----------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=../..

#
# List all of the subdirectories that we will compile.
#

TOOLNAME=staticprofiler

# USEDLIBS=parser.a mappercore.a riskeval.a diffengine.a slicer.a dependence.a commons.a 
USEDLIBS=riskeval.a commons.a 

LINK_COMPONENTS = all

include $(LEVEL)/Makefile.common
