##===- projects/sample/tools/Makefile ----------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=../../..

#
# List all of the subdirectories that we will compile.
#

LIBRARYNAME = LLVMDepPass
LOADABLE_MODULE = 1

USEDLIBS = graph.a slicer.a dependence.a 

#LINK_COMPONENTS = all

include $(LEVEL)/Makefile.common
