##===- lib/Transforms/Hello/Makefile -----------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = /home/ryan/Projects/llvm/src

LLVM_SRC_ROOT = /home/ryan/Projects/llvm/src
LLVM_OBJ_ROOT = /home/ryan/Projects/llvm/src

LIBRARYNAME = LLVMMDMap
LOADABLE_MODULE = 1
USEDLIBS =

include $(LEVEL)/Makefile.common

