##===- projects/sample/tools/Makefile ----------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#

TOOLNAME=testdecoder

LIBRARYNAME=patchdecoder

LLVMLIBS=LLVMSupport.a LLVMCore.a

include $(LEVEL)/Makefile.common
