##===- projects/sample/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=../..

#
# List all of the subdirectories that we will compile.
#
DIRS=CommonsDriver CostModelDriver RiskEvalDriver MapperDriver MatcherDriver DecoderDriver SlicerDriver ScratchDriver

include $(LEVEL)/Makefile.common
