#!/bin/bash
#################################################
# Simple alternator between ld.dummy and ld.real
# Author: Ryan
################################################


BASEDIR=$(dirname $0) # not safe

REAL=
DUMMY=
while getopts "rd" OPT
do
    case $OPT in
      r)
        REAL=1
        ;;
      d)
        DUMMY=1
        ;;
      ?)
        echo "$0 -r(d)"
        exit 1
        ;;
    esac
done

if [ -z "$REAL" -o -z "$DUMMY" ]; then
    if [ ! -z "$REAL" ]; then
        cp $BASEDIR/ld.real $BASEDIR/ld
        exit 0
    fi

    if [ ! -z "$DUMMY" ]; then
        cp $BASEDIR/ld.dummy $BASEDIR/ld
        exit 0
    fi
else
    echo "Option conflicts."
    exit 1
fi


######alternate
if [ ! -f $BASEDIR/ld ]; then
    echo "Cannot find $BASEDIR/ld"
    exit 1
fi
if [ ! -f $BASEDIR/ld.real ]; then
    echo "Cannot find $BASEDIR/ld.real"
    exit 1
fi
if [ ! -f $BASEDIR/ld.dummy ]; then
    echo "Cannot find $BASEDIR/ld.dummy"
    exit 1
fi
diff $BASEDIR/ld $BASEDIR/ld.dummy > /dev/null
if [ $? -eq 0 ]; then
    echo "switching ld to ld.real"
    cp $BASEDIR/ld.real $BASEDIR/ld
    exit 0
fi
diff $BASEDIR/ld $BASEDIR/ld.real > /dev/null
if [ $? -eq 0 ]; then
    echo "switching ld to ld.dummy"
    cp $BASEDIR/ld.dummy $BASEDIR/ld
    exit 0
fi
echo "ld is neither ld.dummy nor ld.real. Not switching!"
exit 1
